const demoProducts=[
{id:"1",name:"Caramel Latte",category:"Coffee",price:4.5,description:"Smooth espresso, steamed milk and caramel.",image:"images/caramel-latte.jpg"},
{id:"2",name:"Cappuccino",category:"Coffee",price:4,description:"Rich espresso with velvety foam.",image:"images/cappuccino.jpg"},
{id:"3",name:"Cold Brew",category:"Cold Drinks",price:4.25,description:"Slow-steeped coffee served chilled.",image:"images/cold-brew.jpg"},
{id:"4",name:"Chocolate Croissant",category:"Pastry",price:3.5,description:"Buttery pastry with chocolate filling.",image:"images/chocolate-croissant.jpg"},
{id:"5",name:"Matcha Latte",category:"Tea",price:4.75,description:"Creamy ceremonial-style matcha latte.",image:"images/matcha-latte.jpg"},
{id:"6",name:"Mocha",category:"Coffee",price:4.75,description:"Espresso, chocolate and steamed milk.",image:"images/mocha.jpg"}];

let products=JSON.parse(localStorage.getItem("beanBloomProducts")||"null")||demoProducts;
let cart=JSON.parse(localStorage.getItem("beanBloomCart")||"[]");
let user=JSON.parse(localStorage.getItem("beanBloomUser")||"null");

const app=document.getElementById("app");
const money=n=>"$"+Number(n).toFixed(2);
const save=()=>{localStorage.setItem("beanBloomProducts",JSON.stringify(products));localStorage.setItem("beanBloomCart",JSON.stringify(cart));};
const updateHeader=()=>{document.getElementById("cartCount").textContent=cart.length;document.getElementById("accountBtn").href=user?"#admin":"#login";document.getElementById("accountBtn").textContent=user?"♙":"🔒";};

function productCard(p,admin=false){
 return `<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}"><span>${p.category}</span></div><div class="product-info"><h3>${p.name}</h3><p>${p.description}</p><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add-btn" onclick="addToCart('${p.id}')">+</button></div>${admin?`<div class="admin-actions"><button onclick="editProduct('${p.id}')">Edit</button><button onclick="deleteProduct('${p.id}')">Delete</button></div>`:""}</div></article>`;
}
function home(){
 app.innerHTML=`<section class="hero"><div class="hero-copy"><span class="eyebrow">Freshly brewed every day</span><h1>Good coffee.<br><em>Good moments.</em></h1><p>Handcrafted drinks, warm pastries, and a cozy place to slow down. Your daily cup starts here.</p><div class="hero-buttons"><a class="btn" href="#menu">Explore Menu →</a><a class="btn ghost" href="#about">Our Story</a></div><div class="mini-stats"><span><b>100%</b> Fresh beans</span><span><b>7:00–20:00</b> Daily</span></div></div><div class="hero-art"><div class="bloom-glow"></div><div class="hero-coffee"><span>☕</span></div><span class="art-note">Grown in the Cambodian highlands</span></div></section>
<section class="section featured"><div class="section-head"><div><span class="eyebrow">Customer favorites</span><h2>Made for your mood</h2></div><a class="text-link" href="#menu">View full menu →</a></div><div class="product-grid">${products.slice(0,3).map(productCard).join("")}</div></section>
<section class="story-band"><div class="story-photo"><div class="coffee-circle">☕</div></div><div><span class="eyebrow">Why Bean & Bloom?</span><h2>A little café with a lot of heart.</h2><p>We believe coffee tastes better when it is made with good beans, careful hands, and a welcoming smile. Come in, stay awhile, and make yourself at home.</p><a class="btn ghost" href="#about">Read our story</a></div></section>
<section class="section values"><span class="eyebrow">Simple things, done well</span><h2>What we care about</h2><div class="value-grid"><div class="value"><div class="value-icon">☕</div><h3>Quality coffee</h3><p>Freshly roasted beans and carefully balanced recipes.</p></div><div class="value"><div class="value-icon">♡</div><h3>Warm service</h3><p>Friendly faces and a space where everyone belongs.</p></div><div class="value"><div class="value-icon">✦</div><h3>Good energy</h3><p>A calm corner for work, chats, and little celebrations.</p></div></div></section>`;
}
function menu(){
 app.innerHTML=`<section class="section menu-page"><div class="center-head"><span class="eyebrow">Our menu</span><h1>Something delicious<br>for every moment.</h1><p>From your first coffee of the morning to a sweet afternoon break.</p></div><div class="menu-tools"><div class="pills">${["All","Coffee","Cold Drinks","Tea","Pastry"].map(c=>`<button onclick="filterMenu('${c}',this)">${c}</button>`).join("")}</div><label class="search">🔎 <input id="searchMenu" placeholder="Search menu..." oninput="renderMenu()"></label></div><div class="product-grid" id="menuGrid"></div></section>`;
 renderMenu();
}
let currentCat="All";
function filterMenu(c,el){currentCat=c;document.querySelectorAll(".pills button").forEach(b=>b.classList.remove("active"));el.classList.add("active");renderMenu();}
function renderMenu(){const q=(document.getElementById("searchMenu")?.value||"").toLowerCase();const shown=products.filter(p=>(currentCat==="All"||p.category===currentCat)&&p.name.toLowerCase().includes(q));document.getElementById("menuGrid").innerHTML=shown.length?shown.map(productCard).join(""):`<div class="empty">☕<p>No items found.</p></div>`;if(document.querySelector(".pills button"))document.querySelectorAll(".pills button")[["All","Coffee","Cold Drinks","Tea","Pastry"].indexOf(currentCat)].classList.add("active");}
function about(){app.innerHTML=`<section class="section about"><div class="split"><div><span class="eyebrow">Our story</span><h1>Born from a love of coffee & community.</h1><p>Bean & Bloom started with one simple idea: create a neighborhood café where excellent coffee and genuine connection come together.</p><p>Our baristas take time with every cup, using thoughtfully selected beans and fresh ingredients. Whether you are meeting a friend, studying, or enjoying five quiet minutes alone, there is a seat for you here.</p><a class="btn" href="#menu">Taste the menu</a></div><div class="about-art"><div class="about-card"><div style="font-size:50px">☕</div><strong>Since 2024</strong><span>Made with care</span></div></div></div><div class="about-stats"><div><b>6+</b><span>Signature drinks</span></div><div><b>7 days</b><span>Open every week</span></div><div><b>100%</b><span>Good vibes</span></div></div></section>`}
function contact(){app.innerHTML=`<section class="section contact"><div class="center-head"><span class="eyebrow">Come say hello</span><h1>We'd love to see you.</h1><p>Drop by for a cup, a chat, or a little quiet time.</p></div><div class="contact-grid"><div class="contact-card"><div class="contact-icon">📍</div><h3>Visit us</h3><p>123 Coffee Street<br>Phnom Penh, Cambodia</p></div><div class="contact-card"><div class="contact-icon">◷</div><h3>Opening hours</h3><p>Monday – Sunday<br>7:00 AM – 8:00 PM</p></div><div class="contact-card"><div class="contact-icon">✉</div><h3>Email us</h3><p>hello@beanandbloom.com<br>+855 12 345 678</p></div></div><form class="contact-form" onsubmit="event.preventDefault();alert('Thanks! Your message has been received.')"><h2>Send us a message</h2><div class="form-grid"><input placeholder="Your name" required><input type="email" placeholder="Email address" required></div><textarea placeholder="How can we help?" rows="5" required></textarea><button class="btn">Send message</button></form></section>`}
function login(){authPage(true)}
function register(){authPage(false)}
function authPage(isLogin){
 app.innerHTML=`<section class="auth-page"><div class="auth-card"><div class="auth-icon">☕</div><span class="eyebrow">Bean & Bloom</span><h1>${isLogin?"Welcome back":"Create your account"}</h1><p>${isLogin?"Sign in to access your account and dashboard.":"Join us and manage your coffee shop account."}</p><form id="authForm">${!isLogin?'<input id="name" placeholder="Full name">':""}<input id="email" type="email" placeholder="Email address" required><input id="password" type="password" placeholder="Password" minlength="6" required><div id="authError"></div><button class="btn full">${isLogin?"Sign in":"Create account"}</button></form>${isLogin?'<a class="small-link" href="#forgot">Forgot password?</a>':""}<p class="switch">${isLogin?"New here?":"Already have an account?"} <a href="#${isLogin?"register":"login"}">${isLogin?"Create an account":"Sign in"}</a></p><p class="demo-hint">Demo: admin@beanandbloom.com / coffee123</p></div></section>`;
 document.getElementById("authForm").onsubmit=e=>{e.preventDefault();const email=document.getElementById("email").value.trim();const password=document.getElementById("password").value;const err=document.getElementById("authError");let saved=JSON.parse(localStorage.getItem("beanBloomAccount")||"null");if(isLogin){if(!saved||saved.email!==email||saved.password!==password){err.innerHTML='<div class="error">Invalid email or password.</div>';return}}else{if(saved&&saved.email===email){err.innerHTML='<div class="error">An account with this email already exists.</div>';return}if(password.length<6){err.innerHTML='<div class="error">Password must be at least 6 characters.</div>';return}saved={email,password,name:document.getElementById("name").value||"Coffee Shop Admin"};localStorage.setItem("beanBloomAccount",JSON.stringify(saved));}user={email:saved.email,name:saved.name||"Admin"};localStorage.setItem("beanBloomUser",JSON.stringify(user));updateHeader();location.hash="#admin";};
}
function forgot(){app.innerHTML=`<section class="auth-page"><div class="auth-card"><div class="auth-icon">✉</div><span class="eyebrow">Account recovery</span><h1>Reset your password</h1><p>Enter your email and we will show a demo reset message.</p><form onsubmit="event.preventDefault();document.getElementById('resetMsg').innerHTML='<div class=success>Demo reset link sent. In a real project, connect a backend/email service.</div>'"><input type="email" placeholder="Email address" required><button class="btn full">Send reset link</button></form><div id="resetMsg"></div><p class="switch"><a href="#login">Back to sign in</a></p></div></section>`}
function admin(){
 if(!user){location.hash="#login";return}
 app.innerHTML=`<section class="section admin"><div class="admin-head"><div><span class="eyebrow">Management</span><h1>Admin dashboard</h1><p>Manage your menu products using browser localStorage.</p></div><button class="btn ghost" onclick="logout()">Sign out</button></div><div class="dashboard-grid"><div class="panel"><div class="panel-head"><h2 id="formTitle">Add product</h2><button id="cancelEdit" style="display:none">Cancel</button></div><form class="product-form" id="productForm"><input id="pName" placeholder="Product name" required><select id="pCat"><option>Coffee</option><option>Cold Drinks</option><option>Tea</option><option>Pastry</option></select><input id="pPrice" type="number" step="0.01" min="0" placeholder="Price" required><input id="pImage" placeholder="Image path or URL" value="images/caramel-latte.jpg"><textarea id="pDesc" placeholder="Description" rows="4"></textarea><button class="btn full" id="saveProduct">Add product</button></form></div><div class="panel"><div class="panel-head"><h2>Products <span>${products.length}</span></h2></div><div class="admin-products">${products.map(p=>productCard(p,true)).join("")}</div></div></div></section>`;
 document.getElementById("productForm").onsubmit=e=>{e.preventDefault();const id=document.getElementById("productForm").dataset.edit;const data={name:pName.value,category:pCat.value,price:Number(pPrice.value),description:pDesc.value,image:pImage.value||"images/caramel-latte.jpg"};if(id){products=products.map(p=>p.id===id?{...p,...data}:p)}else{products.unshift({id:String(Date.now()),...data})}save();admin()};
 document.getElementById("cancelEdit").onclick=admin;
}
function editProduct(id){const p=products.find(x=>x.id===id);if(!p)return;admin();setTimeout(()=>{const f=document.getElementById("productForm");f.dataset.edit=id;document.getElementById("formTitle").textContent="Edit product";document.getElementById("saveProduct").textContent="Update product";document.getElementById("cancelEdit").style.display="block";pName.value=p.name;pCat.value=p.category;pPrice.value=p.price;pDesc.value=p.description;pImage.value=p.image},0)}
function deleteProduct(id){if(confirm("Delete this product?")){products=products.filter(p=>p.id!==id);save();admin()}}
function logout(){user=null;localStorage.removeItem("beanBloomUser");updateHeader();location.hash="#home"}
function addToCart(id){const p=products.find(x=>x.id===id);if(p){cart.push(p);save();updateHeader();openCart()}}
function openCart(){renderCart();document.getElementById("cartOverlay").classList.add("open")}
function renderCart(){const el=document.getElementById("cartContent");if(!cart.length){el.innerHTML='<div class="empty">🛍<p>Your cart is empty.</p><a class="btn" href="#menu" onclick="closeCart()">Browse Menu</a></div>';return}const total=cart.reduce((s,p)=>s+p.price,0);el.innerHTML=`<div>${cart.map((p,i)=>`<div class="cart-item"><img src="${p.image}"><div><strong>${p.name}</strong><span>${money(p.price)}</span></div><button onclick="removeFromCart(${i})">✕</button></div>`).join("")}</div><div class="cart-total"><span>Total</span><strong>${money(total)}</strong></div><button class="btn full" onclick="openCheckout()">Checkout & Pay</button>`}
function removeFromCart(i){cart.splice(i,1);save();updateHeader();renderCart()}
function closeCart(){document.getElementById("cartOverlay").classList.remove("open")}
function openCheckout(){if(!cart.length)return;closeCart();const total=cart.reduce((s,p)=>s+p.price,0);document.getElementById("checkoutContent").innerHTML=`<div class="checkout-layout"><div><span class="eyebrow">Secure checkout</span><h2>Scan & pay</h2><p>Scan the ACLEDA QR code with your banking app to pay for your coffee order.</p><div class="checkout-total"><span>Order total</span><strong>${money(total)}</strong></div>${cart.map(p=>`<div class="checkout-items">${p.name} — ${money(p.price)}</div>`).join("")}<p>After payment, click “I have completed payment”.</p></div><div class="qr-panel"><strong>ACLEDA BANK</strong><small> Scan. Pay Done.</small><img src="images/acleda-qr.png" alt="ACLEDA payment QR code"><strong>KONG CHANSOPHEARITH</strong><p><button class="btn full" onclick="paymentDone()">✓ I have completed payment</button></p></div></div>`;document.getElementById("checkoutOverlay").classList.add("open")}
function paymentDone(){document.getElementById("checkoutContent").innerHTML=`<div class="payment-success"><div class="success-icon">✓</div><span class="eyebrow">Thank you</span><h2>Payment submitted</h2><p>Your order has been recorded as paid for this demo checkout. Payment is not automatically verified.</p><button class="btn" onclick="finishPayment()">Back to menu</button></div>`}
function finishPayment(){cart=[];save();updateHeader();document.getElementById("checkoutOverlay").classList.remove("open");location.hash="#menu"}
function route(){const r=location.hash.replace("#","")||"home";window.scrollTo(0,0);document.getElementById("mobileMenu").classList.remove("open");if(r==="home")home();else if(r==="menu")menu();else if(r==="about")about();else if(r==="contact")contact();else if(r==="login")login();else if(r==="register")register();else if(r==="forgot")forgot();else if(r==="admin")admin();else home();}
document.getElementById("cartBtn").onclick=openCart;document.getElementById("closeCart").onclick=closeCart;document.getElementById("cartOverlay").onclick=e=>{if(e.target.id==="cartOverlay")closeCart()};document.getElementById("closeCheckout").onclick=()=>document.getElementById("checkoutOverlay").classList.remove("open");document.getElementById("checkoutOverlay").onclick=e=>{if(e.target.id==="checkoutOverlay")e.currentTarget.classList.remove("open")};document.getElementById("hamb").onclick=()=>document.getElementById("mobileMenu").classList.toggle("open");window.addEventListener("hashchange",route);updateHeader();route();